Repository timja/github-comment-ops, pull requests merged in 2022-08, with the labels that each got.

#70 Handle comments with multiple lines
  app/matchers.js
  app/matchers.test.js
  app/router.js
Labels: bug

#72 refactor
  app/commands.js
  app/commands.test.js
  app/router.js
Labels: chore

#77 Add winston for logging
  app/commands/actor-request.js
  app/commands/close-command.js
  app/commands/label-command.js
  app/commands/remove-label-command.js
  app/commands/reopen-command.js
  app/commands/reviewer-command.js
  app/commands/transfer-command.js
  app/logger.js
  app/router.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#79 Cleanup error logging
  app/commands/close-command.js
  app/commands/label-command.js
  app/commands/remove-label-command.js
  app/commands/reopen-command.js
  app/commands/reviewer-command.js
  app/commands/transfer-command.js
  app/default-config.js
  app/github.js
  app/router.js
Labels: enhancement

#80 Disable commands by default
  .github/comment-ops.yml
  README.md
  app/default-config.js
Labels: enhancement

#82 Don't error when closing/opening pull request
  app/command-enabled.js
  app/commands/close-command.js
  app/commands/reopen-command.js
Labels: bug
