Repository timja/github-comment-ops, pull requests merged in 2022-07, with the labels that each got.

#23 Add helm chart
  .github/workflows/helm.yml
  .prettierignore
  charts/github-comment-ops/.helmignore
  charts/github-comment-ops/Chart.yaml
  charts/github-comment-ops/templates/NOTES.txt
  charts/github-comment-ops/templates/_helpers.tpl
  charts/github-comment-ops/templates/deployment.yaml
  charts/github-comment-ops/templates/hpa.yaml
  charts/github-comment-ops/templates/ingress.yaml
  charts/github-comment-ops/templates/service.yaml
  charts/github-comment-ops/templates/serviceaccount.yaml
  charts/github-comment-ops/templates/tests/test-connection.yaml
  charts/github-comment-ops/values.yaml
Labels: enhancement

#28 Add configuration to release notes categories
  .github/release.yml
Labels: chore

#29 Add bug to release config
  .github/release.yml
Labels: chore

#34 feat: add link to repo's labels in addLabel error message
  app/github.js
Labels: enhancement

#37 Update chart
  charts/github-comment-ops/Chart.yaml
  charts/github-comment-ops/README.md
Labels: chore

#38 chore: complete the README
  README.md
  charts/github-comment-ops/README.md
  charts/github-comment-ops/README.md.gotmpl
Labels: chore

#47 Update /reviewer docs
  README.md
Labels: documentation

#48 Use regex split to allow mix of space and comma for reviewers
  app/converters.js
  app/converters.test.js
Labels: enhancement

#49 Bump chart version in docs
  charts/github-comment-ops/README.md
Labels: documentation

#50 Run tests on CI
  .github/workflows/ci.yml
Labels: tests

#55 Add eslint and fix eslint issues
  .eslintrc
  app/converters.js
  app/github.js
  app/matchers.js
  index.js
  package-lock.json
  package.json
Labels: chore

#60 Config based approach to commands
  README.md
  app/command-enabled.js
  app/command-enabled.test.js
  app/commands.js
  app/commands.test.js
  app/commands/actor-request.js
  app/commands/close-command.js
  app/commands/command.js
  app/commands/label-command.js
  app/commands/remove-label-command.js
  app/commands/reopen-command.js
  app/commands/reviewer-command.js
  app/commands/transfer-command.js
  app/default-config.js
  app/github.js
  app/matchers.js
  app/router.js
  docker-compose.yml
  package-lock.json
  package.json
Labels: enhancement
